version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "Add support for apt-based dependencies during both compile and runtime"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
